title: Kendra Plant # your name (or website title) here
logo: "/images/kendra_plant_circle_profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer and Coding Dojo Bootcamp Graduate.
  <br><br>
  CompTIA IT Operations Specialist and Project+ Certified Technologist. Also knitting, theater, animals.
  <br><br>
  <a href="https://www.linkedin.com/in/kendraplant/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
